<ul class="form-list" id="payment_form_Coinmoney" style="display:none;">
  <div style="float:left; width: 100%; font-size: 11px; padding: 10px 0;">
    Click "Continue"<br />
    The system will process your order automatically.
  </div>
</ul>

<script>
  function changePaymentSystem(){

    if (document.getElementById("p_method_Coinmoney").checked == true) {
      var request = new Ajax.Request(
        '/coinmoney_callback/index/send/',
        {
          method:'post',
          onComplete: function(transport) {

            if (transport && transport.responseText) {
              var json = transport.responseText.evalJSON();
              if(json['redirect_url']) {
                location = json['redirect_url'];
              }
            }
          },
          onSuccess: this.onSave,
          onFailure: checkout.ajaxFailure.bind(checkout)
        }
      );
    }
  }
  
  (function() {
    $$('#payment-buttons-container button')[0].observe('click', function(event) {
      changePaymentSystem();
    });
  })();
</script>

